name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'dotnet-app2-isw-rojas' }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
       cd Isw3-Test
       dotnet test --no-build --verbosity normal
    - name: Docker build
      uses: docker/setup-buildx-action@v2
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
       username: ${{secrets.USERNAME}}
       password: ${{secrets.PASSWORD}}
       
    - name: build and push
      id: build-and-push
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        context: Isw3-integrador.Controller
        file: Isw3-integrador.Controller/Dockerfile
        push: true
        
        builder: ${{ steps.buildx.outputs.name }}
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          juanrojas09/integrador2-isw3-dotnet
  
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache


    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest}}
  
  
    - name: checkout 
      uses: actions/checkout@v2
    
    - name: Docker build
      run: docker login --username=_ --password=${{secrets.HEROKU_API_KEY}} registry.heroku.com
      
    - name: Heroku Publish
      run: | 
         heroku container:push web -a 'dotnet-app2-isw-rojas'
         heroku container:release web -a 'dotnet-app2-isw-rojas'
